crudproject/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
]

employee/urls.py
from django.urls import path
from employee import views


app_name = "employee"

urlpatterns = [
    path('',views.home,name='home'),  
    path('userregister/',views.userregister,name='userregister'),  
    path('userlogin/',views.userlogin,name='userlogin'),
    path('userlogout/',views.userlogout,name="userlogout"),    
    path('userlist/',views.userlist,name='userlist'),  
    path('userleave/',views.userleave,name="userleave"),
    path('userdelete/<int:id>',views.userdelete,name="userdelete"),
    path('userupdate/<int:id>',views.userupdate,name="userupdate"),
    path('usernewpassword/',views.usernewpassword,name="usernewpassword"),   
    path('usermakepassword/<int:id>',views.usermakepassword,name="usermakepassword"),   
    path('userapplyleave/<int:id>',views.userapplyleave,name="userapplyleave"),
    # path('new/',views.new,name="new"),   

    
]

employee/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Employee(AbstractUser):
    email = models.CharField(max_length=255,unique=True)
    password = models.CharField(max_length=255)

    def __str__(self):
        return self.email
    
class leave(models.Model):
    user = models.EmailField( null=True,editable=False)
    start_date = models.DateField()
    end_date = models.DateField()     
    remaining_leave = models.IntegerField(null=True)
    reason = models.TextField() 
    approved  = models.BooleanField(default=False)  

employee/forms.py
# from django import forms
# from .models import Employee



# class EmployeeForm(forms.ModelForm):
# 	class Meta:
# 		model = Employee
# 		fields =  ['username','firstname','lastname','email','password']	



	

employee/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from .models import Employee,leave
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.hashers import make_password
from django.contrib import messages

def userupdate(request,id):
    data = Employee.objects.get(id=id)
    print("data-----------",data)
    if request.method=="POST":
        data.first_name=request.POST['firstname']
        data.last_name=request.POST['lastname']
        data.save()
        return redirect('employee:userlist')
    else:
        return render(request,"update.html",{'data':data})


def userapplyleave(request,id):
    data = Employee.objects.get(id=id)
    if request.method=="POST":
        startdate=request.POST['startdate']
        enddate = request.POST['enddate']
        reason = request.POST['reason']
        
        data = leave(user=request.user,start_date=startdate,end_date=enddate,reason=reason)
        data.save()
        print('value---------------',leave)
        return redirect("employee:userleave")
    else:
        return render(request,"apply_leave.html",{'data':data})


def home(request):
    return render(request,"index.html")

def userlogin(request):
    if request.method=="POST":
        username=request.POST['username']
        password=request.POST['password']
        user=authenticate(request,username=username,password=password)
        print("user---------------",user)
        
        if user is not None:
            login(request,user) 
            messages.success(request,"login sucessfully")
            return redirect("employee:home")
        else:
            messages.warning(request,"Please Enter Email And Password")
            return render(request,"login.html")
    else:
        return render(request,"login.html")

def userregister(request):
    if request.method=="POST":
        firstname=request.POST['firstname']
        lastname=request.POST['lastname']
        email=request.POST['email']
        password=request.POST['password']
        if email in ('', None) or firstname in ('', None) or lastname in ('', None) or password in ('', None):
            messages.warning(request,"Please fill data")
            return render(request,'register.html')
        else:

            data=Employee.objects.create_user(username=email,first_name=firstname,last_name=lastname,email=email,password=password)
            print("data-------------------------",data)
            return render(request,'login.html',{'data':data})

    else:
        return render(request,'register.html')
    
def userlist(request):  
    data=Employee.objects.all()
    value={'data':data}
    return render(request,"list.html",value)


def userdelete(request,id): 
    Employee.objects.get(id=id).delete()
    return redirect('employee:userlist')

def userleave(request):
    leavedata=leave.objects.all()
    values={'leavedata':leavedata}
    return render(request,"leave.html",values)

def userlogout(request):
    logout(request)
    return redirect('employee:home')


def usernewpassword(request):
    if request.method=="POST":
        oldpassword=request.POST['oldpassword']
        password=request.POST['password']
        confirmpassword=request.POST['confirmpassword']
        if oldpassword and password and confirmpassword:
            if request.user.is_authenticated:
                user = Employee.objects.get(username = request.user.username)
                if not user.check_password(oldpassword):
                    messages.warning(request,"old password is incorrect!")
                else:
                    if password != confirmpassword:
                        messages.warning(request,"new password is not match confirm password!")
                    else:
                        user.set_password(password)
                        user.save()
                        update_session_auth_hash(request, user)
                        messages.success(request,"your password has been changed successfully")
                        return redirect('employee:home')
        else:
            messages.warning(request,"sorry,all fields are required!")
    return render(request,"new_password.html")

def usermakepassword(request,id):
    data = Employee.objects.get(id=id)
    if request.method=="POST":
        password=request.POST['password']
        confirmpassword=request.POST['confirmpassword']
        if password and confirmpassword:
            if request.user.is_authenticated:
                user = Employee.objects.get(username = request.user.username)
                if password != confirmpassword:
                        messages.warning(request,"new password is not match confirm password!")
                else:
                    data=make_password(password=password)
                    data.save()
                    update_session_auth_hash(request, user)
                    messages.success(request,"your password has been changed successfully")
                    return redirect('employee:userlogin')
        else:
            messages.warning(request,"sorry,all fields are required!")
    return render(request,"make_password.html",{'data':data})

templates/apply_leave.html
{%extends 'base.html'%}
{%block content%}


<div class="register">
    <center>
        <h2 class="alert alert-info" ><u>APPLY LEAVE FORM</u></h2>
    </center><br>
    <form action="/userapplyleave/{{request.user.id}}" method="post">
        {% csrf_token %}
        <div class="container col-5"> 
            <div  class="row">
        <div class="mb-3" >
            <label for="exampleInputemail1" class="form-label"><b style="color: aliceblue;">Username:</b></label>
            <input type="email" class="form-control" id="email" name="email" value="{{data.email}}" disabled>
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label"><b style="color: aliceblue;">Start Date:</b></label>
            <input type="date" class="form-control" id="startdate" name="startdate" placeholder="Enter Start Date">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label"><b style="color: aliceblue;">End Date:</b></label>
            <input type="date" class="form-control" id="enddate" name="enddate" placeholder="Enter End Date">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label"><b style="color: aliceblue;">Leave Reason:</b></label>
            <textarea class="form-control" id="reason" name="reason" placeholder="Enter Leave Reason"></textarea>
        </div>
        </br></br></div></div>
        <div class="d-grid gap-2">

            <center> <button type="submit" class="btn btn-primary">Apply</button></center>

        </div>
    </form>

</br></br></br></br></br></br></br></br></br></br></br></br></br></br></br>

</div>



{%endblock%}

templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">


<head>
  <title>Home Page</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js"> </script>
  <style>
    .index {
      background-image: url('/static/image/200.jfif');
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    }

    .card { 
      background-image: url('/static/image/back.jpg');
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    }

    .login {
      background-image: url('/static/image/dark2022.webp');
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    }

    .register {
      background-image: url('/static/image/dark2022.webp');
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    }

    .cpassword {
      background-image: url('/static/image/dark2022.webp');
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    }



    .validation1{
      color: aliceblue;
    }
    .validation2{
      color: aliceblue;
    }
    .validation3{
      color: aliceblue;
    }
    .validation4{
      color: aliceblue;
    }
  </style>
</head>

<body>



  <nav class="navbar navbar-expand-sm navbar-dark bg-dark sticky-top">
    <div class="container-fluid">
      <a
        href="https://www.google.com/search?q=india&source=lmns&bih=969&biw=1920&hl=en&sa=X&ved=2ahUKEwj567Xv3938AhXHiNgFHXKUB04Q_AUoAHoECAEQAA">
        <img class="navbar-brand" src="/static/image/india.png" style="height: 50px; width: 50px; border-radius: 50%;"
          class="rounded-circle"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="mynavbar">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link" href="{%url 'employee:home'%}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'employee:userlist'%}">User's List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'employee:userleave'%}">Leave</a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {%if request.user.is_authenticated%}
          <li class="text-danger" style="margin: 9px 9px 0px 0px;"><b>Hello, 
            <i class="text-primary"><u ><a href="/userapplyleave/{{request.user.id}}">{{request.user.first_name}} {{request.user.last_name}}</a></u></i></b></li>
          <li><a class="nav-link" href="{%url 'employee:userlogout'%}"> LogOut</a></li>
          <li><a class="nav-link" href="{%url 'employee:usernewpassword'%}">Change Password</a></li>
          {%else%}
          <li><a class="nav-link" href="{%url 'employee:userregister'%}">Register</a></li>
          <li><a class="nav-link" href="{%url 'employee:userlogin'%}">Login</a></li>
          {%endif%}
        </ul>
      </div>
    </div>
  </nav>

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
  integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
  crossorigin="anonymous">
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
  integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
  crossorigin="anonymous">
</script>





  {% block content%}


  
  {% endblock%}

  <footer class="text-center text-white" style="background-color: #caced1;">
    <!-- Grid container -->
    <div class="container p-4">
      <!-- Section: Images -->
      <section class="">
        <div class="row">
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div class="bg-image hover-overlay ripple shadow-1-strong rounded" data-ripple-color="light">
              <a
                href="https://www.google.com/search?q=Louvre+Museum&source=hp&ei=khfOY4X1JtT3wAOLtafwBw&iflsig=AK50M_UAAAAAY84lohFHmKgIgBA2vYl7yupBkiG
              RVJDD&ved=0ahUKEwiFhsW599z8AhXUO3AKHYvaCX4Q4dUDCAg&uact=5&oq=Louvre+Museum&gs_lcp=Cgdnd3Mtd2l6EAMyCggAELEDEIMBEEMyBAgAEEMyCggAELEDEIMBEEMy
              BAgAEEMyCwguEIAEEMcBEK8BMgQIABBDMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABFAAWABgxQdoAHAAeACAAYQBiAGEAZIBAzAuMZgBAKABAqABAQ&sclient=gws-wiz">
                <img src="https://mdbcdn.b-cdn.net/img/new/fluid/city/113.webp" class="w-100" /></a>
              <div class="mask" style="background-color: rgba(251, 251, 251, 0.2);"></div>
            </div>
          </div>
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div class="bg-image hover-overlay ripple shadow-1-strong rounded" data-ripple-color="light">
              <a href="https://www.google.com/search?q=eiffel+tower&ei=9xbOY8vJJtTJz7sPgO6J8AE&gs_ssp=eJzj4tDP1TcwyrIwNGC0UjWoMDFPNTNLNbI0M0k1Nkk1SrEyq
            LBISUlOtExNNbYwSE0zTzXw4knNTEtLzVEoyS9PLQIAGiYSdQ&oq=eiffel+towe&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAxgBMgoIABCxAxCDARBDMhEILhCDARCvARDHARCxAxCABD
            IECAAQQzIECAAQQzILCAAQgAQQsQMQgwEyCwgAEIAEELEDEIMBMgsIABCABBCxAxCDATIFCAAQgAQyBQgAEIAEMgUIABCABDoKCAAQRxDWBBCwAzoHCAAQsAMQQzoNCAAQ5AIQ1gQQs
            AMYAToSCC4QxwEQrwEQyAMQsAMQQxgCSgQIQRgASgQIRhgBUKMHWKMHYK0caAFwAXgAgAGTAYgBkwGSAQMwLjGYAQCgAQHIARPAAQHaAQYIARABGAnaAQYIAhABGAg&sclient=gws
            -wiz-serp"><img src="https://mdbcdn.b-cdn.net/img/new/fluid/city/112.webp" class="w-100" /></a>
              <div class="mask" style="background-color: rgba(251, 251, 251, 0.2);"></div>
            </div>
          </div>
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div class="bg-image hover-overlay ripple shadow-1-strong rounded" data-ripple-color="light">
              </a><img src="https://mdbcdn.b-cdn.net/img/new/fluid/city/111.webp" class="w-100" /></a>
              <div class="mask" style="background-color: rgba(251, 251, 251, 0.2);"></div>
            </div>
          </div>
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div class="bg-image hover-overlay ripple shadow-1-strong rounded" data-ripple-color="light">
              <a
                href="https://www.google.com/search?q=paris+france&source=hp&ei=7xjOY4eeAs3X-Qbuq6SIDQ&iflsig=AK50M_UAAAAAY84m_zrX0jgfj2yHytjHnMa8IjNKKI
            aa&gs_ssp=eJzj4tDP1TcwLSzJMmD04ilILMosVkgrSsxLTgUAWiIHxw&oq=par&gs_lcp=Cgdnd3Mtd2l6EAMYADIECC4QQzIECAAQQzIECAAQQzIECAAQQzIECAAQQzIKCC4QxwEQ
            rwEQQzIECAAQQzIECAAQQzILCAAQgAQQsQMQgwEyBAgAEENQAFiaA2DaDWgAcAB4AIABnAGIAZsDkgEDMC4zmAEAoAEB&sclient=gws-wiz">
                <img src="https://mdbcdn.b-cdn.net/img/new/fluid/city/114.webp" class="w-100" /></a>
              <div class="mask" style="background-color: rgba(251, 251, 251, 0.2);"></div>
            </div>
          </div>
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div class="bg-image hover-overlay ripple shadow-1-strong rounded" data-ripple-color="light">
              <a href="https://www.google.com/search?q=taj+mahal+agra&ei=Hx7OY4nrEf3G3LUPt8qviA8&gs_ssp=eJzj4tDP1TfIsUhOMmC0UjWoMLY0NzE3NDJMMTcwSkszS7EyqE
            hJMUpMNbEwME4zNzNPSUn14itJzFLITcxIzFFITC9KBABC0hLR&oq=taj+mahel&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAxgBMgoIABCxAxCDARBDMhMILhCDARCvARDHARCxAxCABBAK
            MgoIABCxAxCDARBDMgoIABCxAxCDARBDMg0IABCABBCxAxCDARAKMg0ILhCABBDHARCvARAKMgoIABCABBCxAxAKMgoIABCABBCxAxAKMgoIABCABBCxAxAKMg0IABCABBCxAxCDARA
            KOgsIABCABBCxAxCDAToECAAQQzoFCAAQgAQ6BwguENQCEEM6EQguEIAEELEDEIMBEMcBENEDOggIABCABBCxAzoECC4QQzoKCC4QsQMQgwEQQzoQCC4QsQMQgwEQxwEQ0QMQQzoHCC4
            QsQMQQzoLCC4QrwEQxwEQgAQ6BwgAELEDEEM6EAguEIMBEK8BEMcBELEDEEM6EQguEIAEELEDEIMBEMcBEK8BOg4ILhCvARDHARCxAxCABDoRCC4QgwEQrwEQxwEQsQMQgAQ6CwguEI
            AEEMcBEK8BSgQIQRgASgQIRhgAUABY5ERg_FdoAnABeACAAdUBiAH9DJIBBTAuOC4ymAEAoAEBwAEB&sclient=gws-wiz-serp">
                <img src="/static/image/taj 2.jpg" class="w-100" style="height: 128px;" /></a>
              <div class="mask" style="background-color: rgba(251, 251, 251, 0.2);"></div>
            </div>
          </div>
          <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
            <div class="bg-image hover-overlay ripple shadow-1-strong rounded" data-ripple-color="light">
              <a href="https://www.google.com/search?q=usa&source=hp&ei=bxnOY6CoGsGa2roP8pyYyAY&iflsig=AK50M_UAAAAAY84nfwh_NNgPOrepQVr8M1wG-JAl11qp&gs_
            ssp=eJzj4tTP1TewTDYvNzBg9GIuLU4EACPwBFA&oq=us&gs_lcp=Cgdnd3Mtd2l6EAMYADIHCC4QsQMQQzIKCC4QxwEQrwEQQzIECC4QQzIKCAAQsQMQgwEQQzIECAAQQzIKCC4Qx
            wEQ0QMQQzILCAAQgAQQsQMQgwEyCwgAEIAEELEDEIMBMggIABCABBCxAzIICC4QsQMQgwE6EAguEMcBEK8BEOoCELQCEEM6DQguENQCEOoCELQCEEM6CgguEOoCELQCEEM6FAgAEOo
            CELQCEIoDELcDENQDEOUCOgUILhCABDoLCC4QgAQQxwEQ0QM6EQguEIAEELEDEIMBEMcBENEDOggILhCABBCxA1CPCFiyCWCOG2gBcAB4AIABpQGIAaYCkgEDMC4ymAEAoAEBsAEL&
            sclient=gws-wiz">
                <img src="https://mdbcdn.b-cdn.net/img/new/fluid/city/116.webp" class="w-100" /></a>
              <div class="mask" style="background-color: rgba(251, 251, 251, 0.2);"></div>
            </div>
          </div>
        </div>
      </section>
      <!-- Section: Images -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(2, 19, 2, 0.49);">
      © 2023 Copyright:
      <a class="text-white" href="https://slickservices.in/">slickservices.in</a>
    </div>
    <!-- Copyright -->
  </footer>




</body>

</html>

templates/index.html
{%extends 'base.html'%}
{%block content%}

  
{%for message in messages%}
<div class="alert alert-success alert-dismissible fade show" role="alert"><button type="button" class="btn-close"
    data-bs-dismiss="alert"></button>
  {{message}}
</div>
{%endfor%}

{%if request.user.is_authenticated%}
<center>
  <div class="alert alert-primary" role="alert">
    <h1 class="col col"><u>Welcome to this page</u></h1>
  </div>
</center>
{%endif%}

<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
      aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
      aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
      aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="img-fluid" src="https://source.unsplash.com/gySMaocSdqs/2700x1200" alt="Los Angeles" class="d-block"
        style="width:120% ">
    </div>
    <div class="carousel-item">
      <img class="img-fluid" src="https://source.unsplash.com/WLUHO9A_xik/2700x1200" alt="Chicago" class="d-block"
        style="width:120% ">
    </div>
    <div class="carousel-item">
      <img class="img-fluid" src="https://source.unsplash.com//C6oPXOatFD8/2700x1200" alt="New York" class="d-block"
        style="width:120% ">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<!-- <------card----->

{%if request.user.is_authenticated%}
<div class="index">
  <div class="row row-cols-1 row-cols-md-3 g-4 " class="card">
    <div class="col" style="margin-left:8%;">
      <div class="card h-100">
        <a href="https://www.w3schools.com/html/"><img src="/static/image/htmlcssjs.jpg" class="card-img-top" alt="..."></a>
        <div class="card-body">
          <h5 class="card-title">Front End Development</h5>
          <p class="card-text">The backend is the server side of the website. It stores
            and arranges data, and also makes sure everything on the client side of the website works fine. It is the
            part
            of the
            website that you cannot see and interact with. It is the portion of software that does not come in direct
            contact with the users. The
            parts and characteristics designers are indirectly accessed application. Activities, like writing
            APIs, creating libraries, and working with system components without user interfaces or programming, are
            also
            included in
            the backend.</p>
        </div>
      </div>
    </div>

    <div class="col" style="margin-left:17% ">
      <div class="card h-100">
        <a href="https://www.djangoproject.com/"><img src="/static/image/o.png" class="card-img-top" alt="..."></a>
        <div class="card-body">
          <h5 class="card-title">Back End Development</h5>
          <p class="card-text">The backend is the server side of the website. It stores
            and arranges data, and also makes sure everything on the client side of the website works fine. It is the
            part
            of the
            website that you cannot see and interact with. It is the portion of software that does not come in direct
            contact with the users. The
            parts and characteristics designers are indirectly accessed application. Activities, like writing
            APIs, creating libraries, and working with system components without user interfaces or programming, are
            also
            included in
            the backend.</p>
        </div>
      </div>
    </div>
  </div>
</div>
{%endif%}


{%endblock%}

templates/register.html
{%extends 'base.html'%}
{%block content%}

{%for message in messages%}
<div class="alert alert-danger alert-dismissible fade show" role="alert"><button type="button" class="btn-close"
    data-bs-dismiss="alert"></button>
    {{message}}
</div>
{%endfor%}
<div class="register">
    <center>
        <h2 class="alert alert-info"><u>REGISTER FORM</u></h2>
    </center><br>
    <form method="post" action="{%url 'employee:userregister'%}" id="mydiv">
        {% csrf_token %}
        <div class="container col-5">
            <div class="row">
                <div class="mb-3 ">
                    <label for="firstname" class="form-label" style="color: aliceblue;"><b>firstname:</b></label>
                    <input type="text" class="form-control" id="firstname" name="firstname" placeholder="Enter Firstname">
                        <h6 class="validation1" hidden >*plz, enter firstname</h6>
                </div>v
               
                <div class="mb-3" >
                    <label for="lastname" class="form-label" style="color: aliceblue;"><b>lastname:</b></label>
                    <input type="text" class="form-control" id="lastname" name="lastname" placeholder="Enter Lastname" onclick="myFunction1()">
                    <P class="validation2" hidden>*plz, enter lastname</P>
                </div>
                
                <div class="mb-3">
                    <label for="email" class="form-label" style="color: aliceblue;"><b>email:</b></label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Enter Email" onclick="myFunction2()">
                    <P class="validation3" hidden >*plz, enter email</P>
                </div>
                
                <div class="mb-3 ">
                    <label for="password" class="form-label"style="color: aliceblue;"><b>password:</b></label>
                    <input type="password" class="form-control" id="password" name="password"placeholder="Enter Password" onclick="myFunction3()">
                    <P class="validation4" hidden>*plz, enter password</P>
                </div>
            </div>
        </div>

        <center> <button type="submit" class="btn btn-primary">Submit</button></center>

<script defer>
function myFunction1(){
    var fillfirst = document.getElementById("firstname")
    var filllast = document.getElementById("lastname")
    console.log(typeof(filllast.value))
    if(fillfirst.value === '' )
    {
        document.getElementsByClassName('validation1')[0].hidden = false;
    }
    else
    {
        document.getElementsByClassName('validation1')[0].hidden = true;
    }
}

function myFunction2(){
    var filllast = document.getElementById("lastname")
    var fillemail = document.getElementById("email")
    console.log(typeof(fillemail.value))
    if(filllast.value === '' )
    {
        document.getElementsByClassName('validation2')[0].hidden = false;
    }
    else
    {
        document.getElementsByClassName('validation2')[0].hidden = true;
    }
}

function myFunction3(){
    var fillemail = document.getElementById("email")
    var fillpassword = document.getElementById("password")
    console.log(typeof(fillpassword.value))
    if(fillemail.value === '' )
    {
        document.getElementsByClassName('validation3')[0].hidden = false;
    }
    else
    {
        document.getElementsByClassName('validation3')[0].hidden = true;
    }
}
</script>

</form>
</br></br></br></br></br></br></br>


{%endblock%}